funding-launchpad/config/routes.rb
Icf::Application.routes.draw do

  match 'press/admin' => 'press#admin'
  resources :press

  mount_roboto

  devise_for :users, :controllers => {:invitations => 'users/invitations', :registrations => 'users/registrations', :confirmations => 'users/confirmations', :omniauth_callbacks => 'users/omniauth_callbacks' }, :skip => [:sessions]
  as :user do
    get 'login' => 'users/registrations#new', :as => :new_user_session
    post 'login' => 'users/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
    get "signup", :to => "users/registrations#new", :as => :new_user_registration
    post "signup", :to => "users/registrations#create", :as => :user_registration
    put "signup", :to => "users/registrations#update", :as => :user_registration
  end
  resources :authentications
  resources :offerings do
    member do
      get :revisions
    end
    resources :photos
    resource  :company
    match 'bank/admin' => 'bank#admin'
    resource  :bank
    resources :contributions
    resources :documents
    resources :links
    match 'events/admin' => 'events#admin'
    resources :events
    match 'auctions/admin' => 'auctions#admin'
    resources :auctions
    match 'rewards/admin' => 'rewards#admin'
    resources :rewards do
      resources :user_rewards
    end
    resources :user_rewards

    match 'investments/share' => 'investments#share'
    resources :investments, :except => [:edit, :show]

    resources :private_investments, :only => [:new, :create]
    resources :questions do
      resources :answers
      get 'page/:page', :action => :index, :on => :collection
    end

    resources :team_members do
      collection do
        put 'update'
      end
    end

    resources :updates do
      member do
        get :revisions
      end
      collection do
        get :admin
      end
    end

    resources :videos do
      collection do
        get 'preview'
      end
    end
    member do
      get :complete
      get :uncomplete
      get :approve
      get :activate
      get :admin
      get :contributors
      get :investors
      get :investment_history
      get :change_status
      get :follow
      get :unfollow
      get :followers
    end
  end

#  resources :contributions
  resources :auction_preferences
  resource :bank
  resources :bid_increments
  resources :default_following_options
  resources :filings
  resources :following_options
  resources :investment_totals
  resources :mycontributions
  resources :myinvestments
  resources :pages
  resources :people do
    member do
      get 'profile'
      get :profile_edit
      post :profile_update
    end
  end
  resources :reviews
  resources :rewards
  resources :user_rewards do
    member do
      get :fulfill
    end
  end
  resources :users do
    member do
      get 'invite'
      get :followings
      get :unfollow
      put :confirm
    end
  end
  resources :contacts, :only => [:new, :create]

  resources :groups do
    member do
      get :members
      put :toggle_offering
    end
  end

  devise_scope :user do
    get "offerings/:offering_id/invitation/new", :to => "users/invitations#new_offering_invite", :as => "new_offering_invitation"
    post "offerings/:offering_id/invitation", :to => "users/invitations#create_offering_invite", :as => "offering_invitation"
    delete "offerings/:offering_id/invitation/:user_id", :to => "users/invitations#destroy_offering_invite", :as => "destroy_offering_invitation"
    post 'offerings/:offering_id/invitation/:id', :to => "users/invitations#resend_offering_invite", :as => "resend_offering_invitation"
    get 'user/accredited', :to => "users#accredited", :as => "accredited_user"
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  match "/unsubscribe" => "users#unsubscribe"
  match "/newsletter" => "users#newsletter"
  match 'about' => 'pages#new_message', :as => 'about', :via => :get
  match 'about' => 'pages#create_message', :as => 'about', :via => :post
  match "/help" => "pages#help"
  match "/my_offerings" => "pages#my_offerings"
  match "/privacy" => "pages#privacy"
  match "/terms" => "pages#terms"
  match "/admin" => "pages#admin"
  match "/settings" => "pages#settings"
  match "/optin" => "pages#optin"
  match "/stripe_validation" => "pages#stripe_validation"
  match "/financials" => "pages#financials"

  #PCP routing
  pcp_constraint = PCPConstraint.new
  root :to => redirect("/offerings/%{name}" % {name: pcp_constraint.name}), :constraints => pcp_constraint
  # funding launchpad routing
  root :to => 'offerings#index'
end

funding-launchpad/app/models/company.rb
class Company < ActiveRecord::Base
  resourcify
  belongs_to :offering

  has_one :address, :as => :addressable
  has_one :phone, :as => :phonable
  has_one :email, :as => :emailable

  attr_accessible :name,
                  :description,
                  :address_attributes,
                  :phone_attributes,
                  :email_attributes

  accepts_nested_attributes_for :address, :allow_destroy => true
  accepts_nested_attributes_for :phone, :allow_destroy => true
  accepts_nested_attributes_for :email, :allow_destroy => true

  validates :name, :presence => true

end

funding-launchpad/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource :offering
  load_and_authorize_resource :company, :through => :offering, :singleton => true

  #currently there is no template for this, so disable
  # def show
    # @company = Company.find(params[:id])
    # respond_to do |format|
      # format.html # show.html.haml
      # format.json { render json: @company }
    # end
  # end

  def new
    @company.build_address
    @company.build_phone
    @company.build_email
  end

  def edit
  end

  def create
    respond_to do |format|
      if @company.save
        format.html {redirect_to admin_offering_path(@offering), notice: "'#{@company.name}' was successfully created"}
      else
        render "new"
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html {redirect_to admin_offering_path(@offering), notice: 'Company was successfully updated.'}
      else
        format.html { render action: "edit" }
      end
    end

  end

end

funding-launchpad/app/views/companies/_address_fields.html.haml
= f.fields_for :address do |address|
  
  = address.hidden_field :content_type, :value => "Company"
  = address.input :address1, :label => "Address Line 1"
  = address.input :address2, :label => "Address Line 2"
  = address.input :city
  = address.input :state
  = address.input :zip_code

funding-launchpad/app/views/companies/_email_fields.html.haml
= f.fields_for :email do |email|
  = email.hidden_field :content_type, :value => "Company"
  = email.input :content, :input_html => {:type => "tel"}, :label => "Email Address"

funding-launchpad/app/views/companies/_form.html.haml
= simple_form_for [@offering, @company], :url => offering_company_url(@offering),  :html => {:class => "form-horizontal"} do |f|
  .row
    .span.well
      .span10
        = f.input :name, :size => "62"
        = f.input :description, :input_html => {:size => "60x10", :class => "wysi span8"}

      .span11
        = form_actions "Save Changes", "Cancel"

funding-launchpad/app/views/companies/_phone_fields.html.haml
= f.fields_for :phone do |phone|
  = phone.hidden_field :content_type, :value => "Company"
  = phone.input :content, :label => "Phone Number"

funding-launchpad/app/views/companies/edit.html.haml
.hero-alt-top  
  .container
    %h2 Modify Your Company Profile
  
.container
  
  = render 'form'

funding-launchpad/app/views/companies/index.html.haml
.hero-alt-top
  .container
    - flash.each do |key, value|
      .flash{:class => key}= value
    %h2 Companies
  
.container
  -if @companies.nil?
    There are currently no companies in the system.
  -else
    %table.table
      - @companies.each do |company|
        %tr
          %td= company.name
          %td= link_to "Detail", company_path(company)
          - if current_user.is_admin?
            %td= link_to "Edit", edit_company_path(company)

funding-launchpad/app/views/companies/new.html.haml
.hero-alt-top
  .container
    %h2 Create A New Company Profile
  
.container
  %p
    You must be affiliated with a company in order to create or manage offerings.  You can
    enter information for your company here and, once complete, you will be able to invite
    others to sign in under your company.
  
  = render 'form'

funding-launchpad/app/views/companies/search.html.haml
.reg_header
  %h1 Select Your Company
  
.reg_body
  %p
    You must be affiliated with a company before you can create or modify offerings.  To
    get affiliated, start by searching for your company here, in case somebody else has
    already entered your company in the system.
    
  = form_for @company do |f|
    .fields= f.label :name
    .fields= f.text_field :name
    .actions= f.submit
    
  %p
    If you're sure your company is not already in the system, you can
    = link_to "Create A New Company Profile", new_company_path