funding-launchpad/config/routes.rb
Icf::Application.routes.draw do

  match 'press/admin' => 'press#admin'
  resources :press

  mount_roboto

  devise_for :users, :controllers => {:invitations => 'users/invitations', :registrations => 'users/registrations', :confirmations => 'users/confirmations', :omniauth_callbacks => 'users/omniauth_callbacks' }, :skip => [:sessions]
  as :user do
    get 'login' => 'users/registrations#new', :as => :new_user_session
    post 'login' => 'users/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
    get "signup", :to => "users/registrations#new", :as => :new_user_registration
    post "signup", :to => "users/registrations#create", :as => :user_registration
    put "signup", :to => "users/registrations#update", :as => :user_registration
  end
  resources :authentications
  resources :offerings do
    member do
      get :revisions
    end
    resources :photos
    resource  :company
    match 'bank/admin' => 'bank#admin'
    resource  :bank
    resources :contributions
    resources :documents
    resources :links
    match 'events/admin' => 'events#admin'
    resources :events
    match 'auctions/admin' => 'auctions#admin'
    resources :auctions
    match 'rewards/admin' => 'rewards#admin'
    resources :rewards do
      resources :user_rewards
    end
    resources :user_rewards

    match 'investments/share' => 'investments#share'
    resources :investments, :except => [:edit, :show]

    resources :private_investments, :only => [:new, :create]
    resources :questions do
      resources :answers
      get 'page/:page', :action => :index, :on => :collection
    end

    resources :team_members do
      collection do
        put 'update'
      end
    end

    resources :updates do
      member do
        get :revisions
      end
      collection do
        get :admin
      end
    end

    resources :videos do
      collection do
        get 'preview'
      end
    end
    member do
      get :complete
      get :uncomplete
      get :approve
      get :activate
      get :admin
      get :contributors
      get :investors
      get :investment_history
      get :change_status
      get :follow
      get :unfollow
      get :followers
    end
  end

#  resources :contributions
  resources :auction_preferences
  resource :bank
  resources :bid_increments
  resources :default_following_options
  resources :filings
  resources :following_options
  resources :investment_totals
  resources :mycontributions
  resources :myinvestments
  resources :pages
  resources :people do
    member do
      get 'profile'
      get :profile_edit
      post :profile_update
    end
  end
  resources :reviews
  resources :rewards
  resources :user_rewards do
    member do
      get :fulfill
    end
  end
  resources :users do
    member do
      get 'invite'
      get :followings
      get :unfollow
      put :confirm
    end
  end
  resources :contacts, :only => [:new, :create]

  resources :groups do
    member do
      get :members
      put :toggle_offering
    end
  end

  devise_scope :user do
    get "offerings/:offering_id/invitation/new", :to => "users/invitations#new_offering_invite", :as => "new_offering_invitation"
    post "offerings/:offering_id/invitation", :to => "users/invitations#create_offering_invite", :as => "offering_invitation"
    delete "offerings/:offering_id/invitation/:user_id", :to => "users/invitations#destroy_offering_invite", :as => "destroy_offering_invitation"
    post 'offerings/:offering_id/invitation/:id', :to => "users/invitations#resend_offering_invite", :as => "resend_offering_invitation"
    get 'user/accredited', :to => "users#accredited", :as => "accredited_user"
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  match "/unsubscribe" => "users#unsubscribe"
  match "/newsletter" => "users#newsletter"
  match 'about' => 'pages#new_message', :as => 'about', :via => :get
  match 'about' => 'pages#create_message', :as => 'about', :via => :post
  match "/help" => "pages#help"
  match "/my_offerings" => "pages#my_offerings"
  match "/privacy" => "pages#privacy"
  match "/terms" => "pages#terms"
  match "/admin" => "pages#admin"
  match "/settings" => "pages#settings"
  match "/optin" => "pages#optin"
  match "/stripe_validation" => "pages#stripe_validation"
  match "/financials" => "pages#financials"

  #PCP routing
  pcp_constraint = PCPConstraint.new
  root :to => redirect("/offerings/%{name}" % {name: pcp_constraint.name}), :constraints => pcp_constraint
  # funding launchpad routing
  root :to => 'offerings#index'
end

funding-launchpad/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :offering
  belongs_to :user
  has_many :answers
  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }

  validates :content, :presence => true

  #Returns an array of users who have participated by asking the question or answering it
  def participants
    users = []
    # add this user
    users << user

    #add each user that has contributed to the thread by answering the question
    users.concat answers.map{|answer| answer.user} if answers.present?

    #return users
    users
  end
end

funding-launchpad/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:show, :index]
  load_and_authorize_resource :offering
  load_and_authorize_resource :question, :through => :offering

  def index
    @questions = Question.where("offering_id IN (?)", @offering.id).order("created_at DESC").page(params[:page]).per(5)
    display_can_invest(@offering)
  end

  def show
  end

  def new
    @show_not_confirmed_message = !current_user.confirmed?
  end

  def create
    @question.user_id = current_user.id
    respond_to do |format|
      if @question.save
        format.html { redirect_to offering_questions_path(@offering), notice: "Question added" }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

end

funding-launchpad/app/views/questions/_question.html.haml
.questions.span
  .span1
    .thumb-container.well
      = image_tag(question.user.person.profile_picture_url(:thumb).to_s)

  .well.span6.question
    .q-a-arrow-border
    .q-a-arrow
    =link_to icon_tag(" Reply", "icon-share-alt icon-mirrored"), new_offering_question_answer_path(@offering, question), :class => "btn btn-reply", :title => "Reply", :remote => !user_signed_in?
    .q-a-header

      %h5
        = "#{question.user.person.first_name} #{question.user.person.last_name}"
      %h6
        = "#{distance_of_time_in_words_to_now(question.created_at)} ago"
    %p.q-a-content

      = link_to "#{question.content}", offering_question_path(@offering, question)

- question.answers.each do |answer|
  .answers.span.offset1
    .span1
      .thumb-container.well{:class => answer.user.has_role?(:offering_admin, @offering) ? "issuer-answer" : ""}
        = image_tag(answer.user.person.profile_picture_url(:thumb).to_s)

    .well.span5.answer{:class => answer.user.has_role?(:offering_admin, @offering) ? "issuer-answer" : ""}
      .q-a-arrow-border
      .q-a-arrow
      .q-a-header
        %h5
          = "#{answer.user.person.first_name} #{answer.user.person.last_name}"
        %h6
          = "#{distance_of_time_in_words_to_now(answer.created_at)} ago"
      %p.q-a-content
        = answer.content

funding-launchpad/app/views/questions/index.html.haml
= render "shared/offering_nav"

.container
  .row
    .span8
      - if @questions.count == 0
        %h4.ac
          There are no questions for this offering.
        %p
          .invest-btn.ac= link_to "Ask a question!", new_offering_question_path(@offering), :class => "btn btn-primary btn-large", :remote => !user_signed_in?
      -else
        %h4.ac
          Want more info about this offering? Browse the Q&A's below or...
        %p
          .invest-btn.ac= link_to "Ask a new question!", new_offering_question_path(@offering), :class => "btn btn-primary btn-large", :remote => !user_signed_in?
        %hr
        #questions-container
          = render @questions

      #question-paginator
        = paginate @questions, :remote => true

    .span4.offering-sidebar
      = render :partial => 'offerings/offering_sidebar'

funding-launchpad/app/views/questions/index.js.erb
$('#questions-container').html('<%= escape_javascript render(@questions) %>');
$('#question-paginator').html('<%= escape_javascript(paginate(@questions, :remote => true).to_s) %>');

funding-launchpad/app/views/questions/new.html.haml
= render "shared/required_modal/confirm_email"

.hero-alt-top
  .container
    %h2 New Question

= simple_form_for [@offering, @question], :html => {:class => '' } do |f|
  .container

    .row
      .span4

        .well.span5
          - flash.each do |key, value|
            .alert{:class => key}= value

          = f.input :content, 
            :label => "What is your question?",
            :required => false,
            :input_html => {:size => "100x10", :class => "span5"}
          = form_actions

funding-launchpad/app/views/questions/show.html.haml
.hero-alt-top
  .container
    %h2= "#{@question.content}"
    = "#{@question.user.person.first_name} #{@question.user.person.last_name} (#{distance_of_time_in_words_to_now(@question.created_at)} ago)"

.container
  %table.table.table-striped.table-bordered.table-condensed
    %tr
      %td{:colspan => "2"}
        - if params[:list] == "i"
          = link_to "See All Answers", offering_question_path(@offering)
        - else
          = pluralize(@question.answers.count, "answer")
          = link_to "See Only Issuer Answers", offering_question_path(@offering, :list => "i")
    - @question.answers.each do |answer|
      - if (params[:list] == "i" && answer.user.has_role?(:offering_admin, @offering)) || params[:list].nil?
        %tr
          %td{:width => "150"}
            - if !answer.user.person.profile_picture.blank?
              = image_tag(answer.user.person.profile_picture_url(:thumb).to_s)
            %br
            = "#{answer.user.person.first_name} #{answer.user.person.last_name}"
            %br
            = "#{distance_of_time_in_words_to_now(answer.created_at)} ago"
          %td= answer.content

  .form-actions-custom-left
    = link_to "Back To Questions", offering_questions_path(@offering), {class: 'btn btn-success pull-left'}
    = button_to "New Answer", new_offering_question_answer_path(@offering, @question), {class: 'btn btn-primary pull-left'}