funding-launchpad/config/routes.rb
Icf::Application.routes.draw do

  match 'press/admin' => 'press#admin'
  resources :press

  mount_roboto

  devise_for :users, :controllers => {:invitations => 'users/invitations', :registrations => 'users/registrations', :confirmations => 'users/confirmations', :omniauth_callbacks => 'users/omniauth_callbacks' }, :skip => [:sessions]
  as :user do
    get 'login' => 'users/registrations#new', :as => :new_user_session
    post 'login' => 'users/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
    get "signup", :to => "users/registrations#new", :as => :new_user_registration
    post "signup", :to => "users/registrations#create", :as => :user_registration
    put "signup", :to => "users/registrations#update", :as => :user_registration
  end
  resources :authentications
  resources :offerings do
    member do
      get :revisions
    end
    resources :photos
    resource  :company
    match 'bank/admin' => 'bank#admin'
    resource  :bank
    resources :contributions
    resources :documents
    resources :links
    match 'events/admin' => 'events#admin'
    resources :events
    match 'auctions/admin' => 'auctions#admin'
    resources :auctions
    match 'rewards/admin' => 'rewards#admin'
    resources :rewards do
      resources :user_rewards
    end
    resources :user_rewards

    match 'investments/share' => 'investments#share'
    resources :investments, :except => [:edit, :show]

    resources :private_investments, :only => [:new, :create]
    resources :questions do
      resources :answers
      get 'page/:page', :action => :index, :on => :collection
    end

    resources :team_members do
      collection do
        put 'update'
      end
    end

    resources :updates do
      member do
        get :revisions
      end
      collection do
        get :admin
      end
    end

    resources :videos do
      collection do
        get 'preview'
      end
    end
    member do
      get :complete
      get :uncomplete
      get :approve
      get :activate
      get :admin
      get :contributors
      get :investors
      get :investment_history
      get :change_status
      get :follow
      get :unfollow
      get :followers
    end
  end

#  resources :contributions
  resources :auction_preferences
  resource :bank
  resources :bid_increments
  resources :default_following_options
  resources :filings
  resources :following_options
  resources :investment_totals
  resources :mycontributions
  resources :myinvestments
  resources :pages
  resources :people do
    member do
      get 'profile'
      get :profile_edit
      post :profile_update
    end
  end
  resources :reviews
  resources :rewards
  resources :user_rewards do
    member do
      get :fulfill
    end
  end
  resources :users do
    member do
      get 'invite'
      get :followings
      get :unfollow
      put :confirm
    end
  end
  resources :contacts, :only => [:new, :create]

  resources :groups do
    member do
      get :members
      put :toggle_offering
    end
  end

  devise_scope :user do
    get "offerings/:offering_id/invitation/new", :to => "users/invitations#new_offering_invite", :as => "new_offering_invitation"
    post "offerings/:offering_id/invitation", :to => "users/invitations#create_offering_invite", :as => "offering_invitation"
    delete "offerings/:offering_id/invitation/:user_id", :to => "users/invitations#destroy_offering_invite", :as => "destroy_offering_invitation"
    post 'offerings/:offering_id/invitation/:id', :to => "users/invitations#resend_offering_invite", :as => "resend_offering_invitation"
    get 'user/accredited', :to => "users#accredited", :as => "accredited_user"
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  match "/unsubscribe" => "users#unsubscribe"
  match "/newsletter" => "users#newsletter"
  match 'about' => 'pages#new_message', :as => 'about', :via => :get
  match 'about' => 'pages#create_message', :as => 'about', :via => :post
  match "/help" => "pages#help"
  match "/my_offerings" => "pages#my_offerings"
  match "/privacy" => "pages#privacy"
  match "/terms" => "pages#terms"
  match "/admin" => "pages#admin"
  match "/settings" => "pages#settings"
  match "/optin" => "pages#optin"
  match "/stripe_validation" => "pages#stripe_validation"
  match "/financials" => "pages#financials"

  #PCP routing
  pcp_constraint = PCPConstraint.new
  root :to => redirect("/offerings/%{name}" % {name: pcp_constraint.name}), :constraints => pcp_constraint
  # funding launchpad routing
  root :to => 'offerings#index'
end

funding-launchpad/app/controllers/press_controller.rb
class PressController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:index]
  load_and_authorize_resource :except => [:index]
  
  # GET /press
  # GET /press.json
  def index
    @press = Press.published.page(params[:page]).per(12)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @press }
      format.js
    end
  end

  # GET /press/1
  # GET /press/1.json
  def show
    @press = Press.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @press }
    end
  end

  # GET /press/new
  # GET /press/new.json
  def new
    @press = Press.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @press }
    end
  end

  # GET /press/1/edit
  def edit
    @press = Press.find(params[:id])
  end

  # POST /press
  # POST /press.json
  def create
    @press = Press.new(params[:press])

    respond_to do |format|
      if @press.save
        format.html { redirect_to @press, notice: 'Press was successfully created.' }
        format.json { render json: @press, status: :created, location: @press }
      else
        format.html { render action: "new" }
        format.json { render json: @press.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /press/1
  # PUT /press/1.json
  def update
    @press = Press.find(params[:id])

    respond_to do |format|
      if @press.update_attributes(params[:press])
        format.html { redirect_to @press, notice: 'Press was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @press.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /press/1
  # DELETE /press/1.json
  def destroy
    @press = Press.find(params[:id])
    @press.destroy

    respond_to do |format|
      format.html { redirect_to press_index_url }
      format.json { head :no_content }
    end
  end

  def admin
    @press = Press.all

    respond_to do |format|
      format.html # admin.html.erb
    end
  end
end

funding-launchpad/app/views/press/_form.html.haml
.well
  = simple_form_for @press do |f|
    = f.error_notification

    .form-inputs
      = f.input :title, input_html: { class: 'span3' }
      = f.input :link, input_html: { class: 'span6' }
      = f.input :description, input_html: { class: 'span6', size:'40x6' }
      = f.input :published_date, input_html: { class: 'span2' }
      = f.label :publisher_logo
      .row.control-group
        .span
          = image_tag(@press.publisher_logo_url(:thumb)) if @press.publisher_logo_url
        .span
          = f.input :publisher_logo, :label => false

      = f.input :publish
      = f.input :feature

    .form-actions
      = f.button :submit, class: "btn-primary"

funding-launchpad/app/views/press/_index.html.haml
-if @press.nil? or @press.count == 0
  %h3
    Press is currently being updated...check back soon
-else
  .row
    .span
      %ul.thumbnails
        - @press.each do |press|

          %li.span3
            = render "press_box", :press => press
  #press-paginator
    = paginate @press, :remote => true

funding-launchpad/app/views/press/_press_box.html.haml
.thumbnail.press-box
  = image_tag(press.publisher_logo_url(:main))
  .caption
    %h4.auto-ellipsis
      - if press.title.length > 45
        = "#{press.title[0..45]}..."
      - else
        = press.title
    %h6
      = press.published_date.to_s(:date_only)
    %p.description.auto-ellipsis
      = "#{press.description[0..150]}..."

    %p
      = link_to "Read More...", press.link, class: "btn btn-primary", target: "_blank"

funding-launchpad/app/views/press/admin.html.haml
.hero-alt-top
  .container
    =render :partial => "shared/flash", :locals => {:flash => flash}
    %h2 Funding Launchpad Press

.container
  %p
    = link_to 'Add Press', new_press_path, class: "btn btn-primary"


  -if @press.nil? or @press.count == 0
    %h3
      We haven't added any press yet :-(
  -else
    %table.table.table-striped.table-bordered
      %tr
        %th Title
        %th Description
        %th Published Date
        %th Publisher Logo
        %th Visible
        %th Featured
        %th Actions

      - @press.each do |press|
        %tr{id: "press_#{press.id}"}
          %td= press.title
          %td= press.description
          %td= press.published_date
          %td= image_tag(press.publisher_logo_url(:thumb))
          %td= press.publish
          %td= press.feature
          %td
            = link_to 'Edit', edit_press_path(press), class: 'btn btn-primary'

funding-launchpad/app/views/press/edit.html.haml
.hero-alt-top
  .container
    %h2 Editing Press

.container
  = render 'form'

  = link_to 'Back', press_admin_path, class: "btn"
  = link_to 'Show', @press, class: "btn btn-primary"

funding-launchpad/app/views/press/index.html.haml
.hero-alt-top
  .container
    =render :partial => "shared/flash", :locals => {:flash => flash}
    %h2 Funding Launchpad Press
.container
  =render "index"

funding-launchpad/app/views/press/new.html.haml
.hero-alt-top
  .container
    %h2 Add new press

.container
  = render 'form'
  = link_to 'Back', press_admin_path, class: "btn"

funding-launchpad/app/views/press/show.html.haml
.hero-alt-top
  .container
    %h2= @press.title
.container
  %p
    %b Link:
    = @press.link
  %p
    %b Description:
    = @press.description
  %p
    %b Published date:
    = @press.published_date
  %p
    %b Visible:
    = @press.publish
  %p
    %b Featured:
    = @press.feature
  %p
  .row
    = image_tag(@press.publisher_logo_url)
  .row
    %br
    = link_to 'Back', press_admin_path, class: "btn"
    = link_to 'Edit', edit_press_path(@press), class: 'btn btn-primary'