Vim-Journey/config/routes.rb
VimJourney::Application.routes.draw do
  resources :users, :entries

  controller :users do
    get 'email-confirmation-sent' => 'users#get_email_confirmation_sent'
    get 'confirm-email' => 'users#get_confirm_email'
  end

  controller :sessions do
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    post 'logout' => 'sessions#destroy'
  end

  controller :statuses do
    post 'statuses' => 'statuses#create'
  end

  controller :likes do
    post 'likes' => 'likes#create'
    delete 'likes' => 'likes#destroy'
  end

  controller :fellows do
    post 'fellows/invite' => 'fellows#invite', :as => 'invite_fellow'
    post 'fellows/approve' => 'fellows#approve'
    post 'fellows/ignore' => 'fellows#ignore'
    post 'fellows/remove' => 'fellows#remove'
  end

  controller :comments do
    post 'comments' => 'comments#create'
  end

  controller :account do
    get 'account' => 'account#index'
  end

  controller :privacy_settings do
    get 'privacy-settings' => 'privacy_settings#index'
    post 'privacy-settings' => 'privacy_settings#update'
  end

  controller :entries do
    get 'journal' => 'entries#new'
  end

  root :to => 'users#new'
end

Vim-Journey/app/models/entry.rb
class Entry < Neo4j::Rails::Model
  property :is_about_a_waypoint, :type => :boolean
  property :waypoint, :type => String
  property :category, :type => String
  property :date, :type => Date
  property :bliss, :type => Fixnum
  property :privacy, :type => Fixnum
  property :description, :type => String
end

Vim-Journey/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new
    @entries = current_user.entries

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    post_to_wall = params[:entry_post_to_wall] == "1"

    respond_to do |format|
      if current_user.add_entry(@entry)
        current_user.add_status(@entry.description) if post_to_wall

        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
end

Vim-Journey/app/helpers/entries_helper.rb
module EntriesHelper
end

Vim-Journey/app/views/entries/_form.html.erb
<%= form_for(@entry, :class => 'form-horizontal') do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <div class="controls">
      <label>Is this about a waypoint?</label>
      <input type="button" class="btn" value="Yes" id="entryHasWaypoint" />
      <input type="button" class="btn" value="No" id="entryHasCategory" />
      <%= f.hidden_field :is_about_a_waypoint %>
    </div>
  </div>

  <div class="control-group hidden" id="entryWaypointControls">
    <%= f.label :waypoint, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :waypoint, [
        "The Pain",
        "The Vision",
        "The Call",
        "The Denial",
        "The Mentor",
        "The Dump",
        "The Commitment",
        "The Trials",
        "The Crisis",
        "The Lesson",
        "The Purpose",
        "The Gift",
        "The Message",
        "The Sharing",
        "The New Life",
        "The Freedom"
      ] %>
    </div>
  </div>

  <div class="control-group hidden" id="entryCategoryControls">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :category, [
        "None", "Life", "Business"
      ] %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :date, {:order => [:month, :day, :year], :start_year => 1900, :end_year => Time.new.year}, {:class => 'span2'} %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :bliss, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :bliss, (1..10).to_a.reverse %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :privacy, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :privacy, [
        ["Public - Everyone", 0], ["Approved - Fellows", 1], ["Private - Only Myself", 2]
      ] %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="entryPostToWallYes">Post to Wall</label>
    <div class="controls">
      <label class="pull-left" style="margin-right: 10px;">
        <input id="entryPostToWallYes" type="radio" name="entry_post_to_wall" value="1" checked="checked"> Yes
      </label>
      <label>
        <input type="radio" name="entry_post_to_wall" value="0"> No
      </label>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :rows => '4', :class => 'input-xxlarge' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Create Journal Entry', :class => 'btn btn-primary' %>
  </div>

<% end %>

Vim-Journey/app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

Vim-Journey/app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <tr>
    <th>Is About A Waypoint</th>
    <th>Waypoint</th>
    <th>Category</th>
    <th>Date</th>
    <th>Bliss</th>
    <th>Privacy</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.is_about_a_waypoint %></td>
    <td><%= entry.waypoint %></td>
    <td><%= entry.category %></td>
    <td><%= entry.date %></td>
    <td><%= entry.bliss %></td>
    <td><%= entry.privacy %></td>
    <td><%= entry.description %></td>
    <td><%= link_to 'Show', entry %></td>
    <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
    <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry', new_entry_path %>

Vim-Journey/app/views/entries/new.html.erb
<script>
  function getEntriesCount() {
    return <%= @entries.count %>;
  }

  var entriesData = <%= @entries.to_a.to_json.html_safe %>;
  if (entriesData.length) entriesData = entriesData.map(function(o) { return o.entry; });
</script>

<ul class="nav nav-tabs">
  <li class="active"><a href="#create" data-toggle="tab">Create a New Journal Entry</a></li>
  <li><a href="#list" data-toggle="tab">List Entries</a></li>
  <li><a href="#graph" data-toggle="tab">Graph Entries</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="create">
    <%= render 'form' %>
  </div>
  <div class="tab-pane" id="list">
    <div class="row">
      <div class="span12">
        <label class="checkbox pull-left" style="padding-right: 10px">
          <input id="life" type="checkbox" checked="checked" /> Life
        </label>
        <label class="checkbox pull-left" style="padding-right: 10px">
          <input id="business" type="checkbox" checked="checked" /> Business
        </label>
        <label class="checkbox pull-left" style="padding-right: 10px">
          <input id="waypoint" type="checkbox" checked="checked" /> Waypoint
        </label>
      </div>
    </div>
    <div class="row">
    <% i = 0
       @entries.to_a.reverse.each do |entry| ; i = i + 1 %>
      <div class="span3 journalEntry<% if entry.category == "Life" %> lifeEntry<% end %><% if entry.category == "Business" %> businessEntry<% end %><% if entry.is_about_a_waypoint %> waypointEntry<% end %>" <% if i > 4 %>style="display: none;"<% end %>>
        <% if entry.is_about_a_waypoint %>
        <p><%= entry.waypoint %></p>
        <% else %>
        <p><%= entry.category %></p>
        <% end %>
        <p><%= entry.date %></p>
        <p><%= entry.description %></p>
        <p><%= entry.bliss %></p>
      </div>
    <% end %>
    </div>
    <div class="row">
      <div class="span12">
        <span class="pull-left">Current</span>
        <span class="pull-right">Beginning</span>
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <div id="slider"></div>
      </div>
    </div>
    <br>
  </div>
  <div class="tab-pane" id="graph">
    <div class="row" id="chart">
      <svg class="span12" style="height: 400px;">
    </div>
  </div>
</div>

Vim-Journey/app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Is About A Waypoint:</b>
  <%= @entry.is_about_a_waypoint %>
</p>

<p>
  <b>Waypoint:</b>
  <%= @entry.waypoint %>
</p>

<p>
  <b>Category:</b>
  <%= @entry.category %>
</p>

<p>
  <b>Date:</b>
  <%= @entry.date %>
</p>

<p>
  <b>Bliss:</b>
  <%= @entry.bliss %>
</p>

<p>
  <b>Privacy:</b>
  <%= @entry.privacy %>
</p>

<p>
  <b>Description:</b>
  <%= @entry.description %>
</p>


<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>